language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
notifications:
  email:
  recipients:
    - KlingmannM@gmail.com
  on_success: always
  on_failed: always
script:
  - nosetests tests
after_success:
  - coveralls
